"""initial schema

Revision ID: 952952992f1f
Revises: 
Create Date: 2026-09-12 14:06:45.080143

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '952952992f1f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('aggregate_type', sa.String(length=32), nullable=False),
    sa.Column('aggregate_id', sa.String(length=36), nullable=False),
    sa.Column('event_type', sa.String(length=128), nullable=False),
    sa.Column('actor_id', sa.String(length=36), nullable=True),
    sa.Column('actor_type', sa.String(length=16), nullable=False),
    sa.Column('reason', sa.String(length=1024), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('previous_event_hash', sa.String(length=64), nullable=True),
    sa.Column('event_hash', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_hash')
    )
    op.create_index('ix_audit_aggregate', 'audit_events', ['aggregate_type', 'aggregate_id'], unique=False)
    op.create_table('wallets',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('owner_id', sa.String(length=36), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('balance', sa.Numeric(precision=19, scale=4), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('owner_id', 'currency', name='uq_wallet_owner_currency')
    )
    op.create_index(op.f('ix_wallets_owner_id'), 'wallets', ['owner_id'], unique=False)
    op.create_table('transfers',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('idempotency_key', sa.String(length=255), nullable=False),
    sa.Column('source_wallet_id', sa.String(length=36), nullable=False),
    sa.Column('destination_wallet_id', sa.String(length=36), nullable=False),
    sa.Column('amount', sa.Numeric(precision=19, scale=4), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('failure_code', sa.String(length=64), nullable=True),
    sa.Column('failure_reason', sa.String(length=1024), nullable=True),
    sa.Column('requested_by', sa.String(length=36), nullable=False),
    sa.Column('requested_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rejected_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['destination_wallet_id'], ['wallets.id'], ),
    sa.ForeignKeyConstraint(['source_wallet_id'], ['wallets.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key')
    )
    op.create_table('authorizations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('transfer_id', sa.String(length=36), nullable=False),
    sa.Column('authorizer_id', sa.String(length=36), nullable=False),
    sa.Column('decision', sa.String(length=8), nullable=False),
    sa.Column('policy_version', sa.String(length=64), nullable=False),
    sa.Column('reason', sa.String(length=1024), nullable=True),
    sa.Column('authorized_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['transfer_id'], ['transfers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_authorizations_transfer_id'), 'authorizations', ['transfer_id'], unique=False)
    op.create_table('compliance_reviews',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('transfer_id', sa.String(length=36), nullable=False),
    sa.Column('reviewer_id', sa.String(length=36), nullable=True),
    sa.Column('decision', sa.String(length=16), nullable=False),
    sa.Column('reason_code', sa.String(length=64), nullable=True),
    sa.Column('reason', sa.String(length=1024), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['transfer_id'], ['transfers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_compliance_reviews_transfer_id'), 'compliance_reviews', ['transfer_id'], unique=False)
    op.create_table('ledger_transactions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('transfer_id', sa.String(length=36), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('posted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['transfer_id'], ['transfers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('transfer_id')
    )
    op.create_table('ledger_entries',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('ledger_transaction_id', sa.String(length=36), nullable=False),
    sa.Column('wallet_id', sa.String(length=36), nullable=False),
    sa.Column('direction', sa.String(length=6), nullable=False),
    sa.Column('amount', sa.Numeric(precision=19, scale=4), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['ledger_transaction_id'], ['ledger_transactions.id'], ),
    sa.ForeignKeyConstraint(['wallet_id'], ['wallets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ledger_entries')
    op.drop_table('ledger_transactions')
    op.drop_index(op.f('ix_compliance_reviews_transfer_id'), table_name='compliance_reviews')
    op.drop_table('compliance_reviews')
    op.drop_index(op.f('ix_authorizations_transfer_id'), table_name='authorizations')
    op.drop_table('authorizations')
    op.drop_table('transfers')
    op.drop_index(op.f('ix_wallets_owner_id'), table_name='wallets')
    op.drop_table('wallets')
    op.drop_index('ix_audit_aggregate', table_name='audit_events')
    op.drop_table('audit_events')
    # ### end Alembic commands ###
